### ISSUE TITLE
Add functionality to remove 'Free' subheading in the register block and a link to external ticketing website

### ISSUE THREAD

**Issue by djamg** [hasgeek/funnel#1478]
**Is your feature request related to a problem? Please describe.**
A few Third Party Organizers are listing their events on hasgeek.com. A few of them are paid events having external registration and ticketing platforms.

**Describe the solution you'd like**
This feature would make it easy for Third Party Organizers to list their paid events
1. Give permissions for a 'Project-Editor' to remove the 'Free' sub-heading in the register block by providing them with a toggle switch in the admin panel.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/22789793/191049130-ca435919-2ab9-49fb-b1bb-f88234f21474.png">
<img width="772" alt="image" src="https://user-images.githubusercontent.com/22789793/191057553-0adfb562-47d8-4aa6-9587-43fe4ec5becc.png">
2. Give permissions for a 'Site-Editor' to add an external link on the 'Register' button. (Avoids spam if the site-editor has controls) [Business Decision]

**Describe alternatives you've considered**
As of now, the organizers are asked to park the links and add the ticket price in the description.

**Additional context**
The participants get a false notion that an event is free by looking at the project page even though it is paid and there may be chances of them showing up at the conference day (since these are physical events).
This feature would make hasgeek.com more friendly for Third-parties to list their events.

**Comment by jace** [comment]
What is the abuse potential in this change? How are we affecting a user's perception of events they see on hasgeek.com?

**Comment by jace** [comment]
There are two existing legacy columns in the Project model that can be used to change the template:

1. `Project.allow_rsvp` (boolean, introduced in #112, Feb 2015)
2. `Project.buy_tickets_url` (string, introduced in #114, Apr 2015)

Optional RSVP was removed in #611 in May 2020 when the notion of project was redefined to require a specific process for hosting an event, and external events were removed from the scope of use. Given this, reintroducing external events will require a new spec for the product.

We can make an interim fix by honouring the legacy fields without waiting for a redefinition of the product.
